import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  input: {
    height: 50,
    marginVertical: 8,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    padding: 10,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  qrCodeContainer: {
    alignItems: 'center',
    marginTop: 20,
    width: '100%',
  },
  camera: {
    flex: 1,
    width: '100%',
    aspectRatio: 1,
  },
  switch: {
    marginVertical: 10,
    alignSelf: 'center',
  },
  verificationResult: {
    fontSize: 18,
    color: 'black',
    margin: 20,
    textAlign: 'center',
  },
  switchContainerBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 35,
    backgroundColor: '#fff',
  },
  switchLabel: {
    fontSize: 16,
    marginHorizontal: 8,
  },
  button: {
    backgroundColor: '#007bff',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
    marginTop: 20,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
  },
  pinContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
  pinInputBox: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderColor: '#cccccc',
    textAlign: 'center',
    fontSize: 20,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  successMessage: {
    fontSize: 24,
    color: 'green',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 20,
    borderWidth: 2,
    borderColor: 'green',
    borderRadius: 10,
    overflow: 'hidden',
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  failMessage: {
    fontSize: 18,
    color: '#D32F2F',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: '#FFCDD2',
    borderRadius: 5,
    marginTop: 20,
    backgroundColor: '#FFEBEE',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
});
