version: '3'
services:
  inro-mobile:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - TZ=Asia/Tokyo
      - EXPO_PUBLIC_SINDRI_API_KEY=${EXPO_PUBLIC_SINDRI_API_KEY}
      - EXPO_PUBLIC_SINDRI_API_URL=${EXPO_PUBLIC_SINDRI_API_URL}
      - EXPO_PUBLIC_CIRCUIT_ID=${EXPO_PUBLIC_CIRCUIT_ID}
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    tty: true
